theme: jekyll-theme-cayman
title: BKT Toolbox
description: Business Kasper Toolbox for Microsoft Office and PowerPoint
google_analytics: UA-4449782-16
show_downloads: false
lang: de
plugins:
  - jemoji
logo: /assets/img/bkt_logo_1.0.svg
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/bkt-open-graph.png